set nocompatible

call plug#begin('/tmp/plugged')

" Add a bunch of random plugins
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
Plug 'tpope/vim-surround'
Plug 'tomtom/tcomment_vim'
Plug 'tpope/vim-fugitive'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'ervandew/supertab'
Plug 'jiangmiao/auto-pairs'

call plug#end()
